name: 🌎 Build and Deploy
# Will uncomment when ready
# on:
  # push:
  #   branches:
  #     - main
    # paths-ignore:
    #   - '.gitignore'
    #   - 'README.md'
    #   - 'biome.json'
    #   - 'commitlint.config.ts'
on: push # Will delete when ready

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    strategy:
      matrix:
        node-version: [20]
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4
      - name: 📦 Setting up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: 🔨 Install dependencies and build
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
        run: |
          pnpm install
          pnpm build
      - name: 🌎 Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}